# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM debian:stable-slim

# Install python3.9
RUN apt-get update -y
RUN apt-get install -y python3.9 python3-pip

# Copy local code to the container image.
ENV APP_HOME /server
WORKDIR $APP_HOME
COPY . ./
COPY config.json /usr/local/lib/python3.9/dist-packages/config.json

# Install production dependencies.
RUN pip3 install --trusted-host pypi.python.org -r requirements-server.txt
RUN pip3 install .

WORKDIR /
ENTRYPOINT ["python3", "-m", "backup.server"]