name: run-pytest
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --project hassio-google-drive-backup --all-extras
    - name: Install fping
      run: sudo apt-get install fping
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run --project hassio-google-drive-backup flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run --project hassio-google-drive-backup flake8 . --count --exit-zero --max-line-length=300 --statistics
    - name: Test with pytest
      run: |
        uv run --project hassio-google-drive-backup pytest hassio-google-drive-backup/tests --junitxml=junit/test-results.xml --cov=hassio-google-drive-backup/backup --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: junit/test-results.xml
      if: ${{ always() }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: junit/**/*.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
